version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_demo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: UniversalReportDB
      MYSQL_USER: demo
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # Map host port 3307 to container port 3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  universalreportheavydemo:
    image: ${DOCKER_REGISTRY-}universalreportheavydemo
    build:
      context: .
      dockerfile: UniversalReportHeavyDemo/Dockerfile
    depends_on:
      - mariadb  # Ensure MariaDB starts first
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=mariadb;Database=UniversalReportDB;User=demo;Password=password;"
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
