site_name: Universal Report Core
site_url: https://tonybierman.github.io/Universal-Report-Core/
repo_url: https://github.com/tonybierman/Universal-Report-Core
site_description: A .NET 8 library for generating reports.
theme:
  name: material  # Changed from 'readthedocs' to 'material'
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.code.copy  # Adds a copy button to code blocks
    - content.tabs  # Enables tabbed content
    - navigation.sections  # Organizes navigation into sections
    - navigation.top  # Adds a "Back to top" button
    - search.suggest  # Enhances search with suggestions
    - search.highlight  # Highlights search terms in results
nav:
  - Home: index.md
  - Getting Started:
    - Prerequisites: prerequisites.md
    - Installing: installing.md
  - Features: features.md
  - Usage: usage.md
  - Running Tests: running-tests.md
  - Deployment: deployment.md
  - Contributing: contributing.md
  - Versioning: versioning.md
  - Authors: authors.md
  - License: license.md
  - Acknowledgments: acknowledgments.md