# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Universal Report Core
email: # Not provided; leave blank or add your email if desired
description: >- # this means to ignore newlines until "baseurl:"
  A .NET 8 library for generating reports with features like tabular data, pagination, sorting, and aggregation.
baseurl: "/Universal-Report-Core" # the subpath of your site
url: "https://tonybierman.github.io" # the base hostname & protocol for your site
twitter_username: # Not provided; leave blank or add your Twitter username
github_username: tonybierman
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Source and destination (since we’re building from docs/)
source: .
destination: ./_site

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  # Additional plugins supported by GitHub Pages
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

author:
  name: "Tony Bierman"
  avatar: "/assets/images/bio-photo.jpg" # Add an image to docs/assets/images/ if desired
  bio: "Creator of Universal Report Core, a .NET 8 library for generating reports."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://tonybierman.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/" # Update with your Twitter URL if applicable
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tonybierman"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/" # Update with your Instagram URL if applicable

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/" # Update with your Twitter URL if applicable
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tonybierman"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/" # Update with your Instagram URL if applicable

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/