title: Universal Report Core
description: A .NET 8 library for generating reports.
baseurl: "/Universal-Report-Core"
url: "https://tonybierman.github.io"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

source: docs
destination: _site

minimal_mistakes_skin: "default"
locale: "en-US"
search: true
search_full_content: true

author:
  name: "Tony Bierman"
  bio: "Creator of Universal Report Core"

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      sidebar:
        nav: "docs-nav"

docs_nav:
  - title: Home
    url: /
  - title: Getting Started
    children:
      - title: Prerequisites
        url: /prerequisites/
      - title: Installing
        url: /installing/
  - title: Features
    url: /features/
  - title: Usage
    url: /usage/
  - title: Running Tests
    url: /running-tests/
  - title: Deployment
    url: /deployment/
  - title: Contributing
    url: /contributing/
  - title: Versioning
    url: /versioning/
  - title: Authors
    url: /authors/
  - title: License
    url: /license/
  - title: Acknowledgments
    url: /acknowledgments/