name: publish

on:
  workflow_dispatch:  # Allow manual execution from GitHub UI
  push:
    branches:
      - 'master'  # Runs on push to master branch
  pull_request:
    branches:
      - '*'  # Runs on any pull request
  release:
    types:
      - published  # Runs when a release is published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget

jobs:
  create_nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          8.0.x

    - name: Copy README.md for NuGet package
      run: cp README.md UniversalReportCore.Packaging/

    # Build all projects before packaging
    - name: Build Projects
      run: dotnet build --configuration Release

    # Pack the UniversalReportCore.Packaging project
    - name: Create NuGet Package
      run: dotnet pack UniversalReportCore.Packaging --configuration Release --output ${{ env.NuGetDirectory }}

    - uses: actions/upload-artifact@v4
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.NuGetDirectory }}/*.nupkg
