name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
  release:
    types:
      - published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget

jobs:
  create_nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          8.0.x

    - name: Copy README.md for NuGet package
      run: cp README.md UniversalReportCore.Packaging/

    # Build the solution file explicitly
    - name: Build Solution
      run: dotnet build UniversalReport.sln --configuration Release

    # Pack the UniversalReportCore.Packaging project
    - name: Create NuGet Package
      run: dotnet pack UniversalReportCore.Packaging/UniversalReportCore.Packaging.csproj --configuration Release --output ${{ env.NuGetDirectory }}

    - uses: actions/upload-artifact@v4
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.NuGetDirectory }}/*.nupkg
